ToDoList/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
from tasks.views import index, register
from django.views.generic import RedirectView
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('register/', register, name='register'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('', RedirectView.as_view(url='tasks/')),
]

tasks/urls.py
from django.urls import path
from .views import index, AddTask, EditTask, DeleteTask
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', index, name='index'),
    path('add/', AddTask.as_view(), name='add'),
    path('<int:pk>/edit/', EditTask.as_view(), name='edit'),
    path('<int:pk>/delete/', DeleteTask.as_view(), name='delete'),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class task(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

tasks/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from .models import task
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from .models import task

# Create your views here.
def index(request):
    if request.user.is_authenticated:
        User = get_user_model()
        user = User.objects.get(id=request.user.id)
        context = {
            'user': user
        }
        return render(request, 'tasks/index.html', context)
    else:
        return HttpResponseRedirect(reverse('login'))

# class index(ListView):
#     model = User
#     template_name = 'tasks/index.html'

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))
    else:
        form = UserCreationForm()
    return render(request, 'tasks/register.html', {'form':form})



# class AddTask(CreateView):
#     model = task
#     fields = ['title']

#     def form_valid(self, form):
#         form.instance.author = self.request.user
#         return super(AddTask, self).form_valid(form)

#     def get_success_url(self):
#         return reverse('index')

# class EditTask(UpdateView):
#     model = task
#     fields = ['title']

#     def get_success_url(self):
#         return reverse('index')

# class DeleteTask(DeleteView):
#     model = task
#     # fields = ['title']

#     def get_success_url(self):
#         return reverse('index')

#     def get(self, request, *args, **kwargs):
#         return self.delete(request, *args, **kwargs)

tasks/templates/tasks/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>To Do List
        </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
              <div class="col-sm-2">
                <div class="mt-3">
                {% block sidebar %}
                    <ul class="sidebar-nav">
                        {% if user.is_authenticated %}
                        <p>{{ request.user }}</p>
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                        
                    {% else %}
                    <li><a href="{% url 'register' %}">Sign Up</a></li>
                    <li><a href="{% url 'login' %}">Login</a></li>
                    {% endif %}
                    </ul>
                {% endblock %}
                </div>
              </div>
              <div class="col-sm-10 ">
                {% block content %}
                {% endblock %}
              </div>
            </div>
          </div>
    </body>
</html>

tasks/templates/tasks/index.html
{% extends "tasks/base.html" %}
{%load crispy_forms_tags %} 
{% block content %}
<div class="mt-3">
    <h3>All tasks</h3>
    <ul>
        {% for task in user.task_set.all %}
            <li>{{ task.title }} <button><a href="{% url 'edit' task.id %}">Edit</a> </button> <button><a href="{% url 'delete' task.id %}">Delete</a></button></li>
        {% endfor %}
    </ul>
    <p><a href="{% url 'add' %}">Add task</a></p>
</div>
{% endblock %}

tasks/templates/tasks/register.html
{%load crispy_forms_tags %} 
<!DOCTYPE html>
<html>
    <head>
        <title>ToDo
        </title>
    </head>
    <body>
        <form method="post">
            {% csrf_token %}
            <p>{{form|crispy}}</p>
            <input type="submit" value="Submit">
        </form>
        
    </body>
</html>

tasks/templates/tasks/task_form.html
{%load crispy_forms_tags %} 
<!DOCTYPE html>
<html>
    <head>
        <title>ToDo
        </title>
    </head>
    <body>
        <form method="post">
            {% csrf_token %}
            <p>{{form|crispy}}</p>
            <input type="submit" value="Submit">
        </form>
        
    </body>
</html>